name: Old poetry
on:
  workflow_dispatch:
    inputs:
        poetry_version:
          description: 'The poetry version'
          required: true
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry self update $INPUT_POETRY_VERSION
      - name: Reproduce error
        run: sh reproduce.sh
